task-29-2-AddTest
tomOsuch/tasks pull request #13
Opened 2021-01-24 23:40 UTC by tomOsuch

2021-01-26 13:57 UTC, tomOsuch commented
Dodałem nowe testy teraz pokrycie metod wychodzi 74% pozostały nie przetestowane metody typu void

2021-01-26 17:08 UTC, marszelun requested changes

2021-01-26 17:08 UTC, marszelun commented on src/test/java/com/crud/tasks/controller/TrelloControllerTest.java
> +
Co to za pusty test?

2021-01-26 17:08 UTC, marszelun commented on src/test/java/com/crud/tasks/trello/facade/TrelloFacadeTest.java
> +        when(trelloFacade.createCard(trelloCardDto)).thenReturn(createdTrelloCardDto);
Dlaczego tutaj akurat sprawdzasz `null`-a? Bardziej wartościowy byłby test, w którym zamockujesz zwracanie jakiejś konkretnej wartości i jednocześnie możesz wtedy zweryfikować wywołanie wysyłki maila w `SimpleMailSender`.

2021-01-26 17:08 UTC, marszelun commented on src/test/java/com/crud/tasks/service/DbServiceTest.java
> +
Puste when-then?

2021-01-26 17:08 UTC, marszelun commented on src/test/java/com/crud/tasks/trello/validator/TrelloValidatorTest.java
> +        assertEquals(1, validTrelloBoard.size());
Przetestowany przypadek, gdzie walidator przepuszcza board, a gdzie odwrotny? Nieprawidłowy board wycięty przez walidator?
To troszkę wygląda jak test napisany, żeby sztucznie wygenerować pokrycie.

2021-01-28 18:12 UTC, marszelun approved these changes

2021-01-28 18:12 UTC, marszelun commented on src/test/java/com/crud/tasks/service/DbServiceTest.java
> -    public void testDeleteByIdTask() {
Hmm.... lepszym rozwiązaniem niż usunięcie testu, byłoby napisanie go tak, żeby coś sprawdzał.
Oczywiście metoda jest typu `void`, ale możesz przy pomocy `verify` upewnić się, czy została wywołana właściwa metoda na repozytorium.

2021-01-28 18:12 UTC, marszelun commented on src/test/java/com/crud/tasks/service/TrelloServiceTest.java
> +        assertNull(resultTrelloCardDto.getBadges());
Widzę że jednak usilnie gdzieś tego `null`-a dajesz. Czy byłby jakiś kłopot w stworzeniu obiektu zawierającego również badge?

2021-01-28 18:44 UTC, tomOsuch commented on src/test/java/com/crud/tasks/service/TrelloServiceTest.java
> +        assertNull(resultTrelloCardDto.getBadges());
W sumie można nad tym popracować tutaj zrobiłem analogicznie jak przy innych testach pisanych w aplikacji ale myślę że nie będzie problemy przy utworzeniu takiego obiektu.

2021-01-29 17:52 UTC, merged